### PR TITLE
Code cleanup and some new features

### PR DESCRIPTION
**Pull request by denilsonsa**
I initially wrote this over one year ago, but never sent a pull request. Now I'm merging everything and sending it!

It includes the commits from /u/Cyrille37, but almost all of them were superseded by newer commits from /u/Sadi58. The only relevant one is using `/usr/bin/env` in the hashbang.

My changes include:

* Forcing Python 2.x at the hashbang.
* Removing trailing whitespace.
* Converting Tabs to spaces.
* Fixing whitespace to conform to [PEP-8](https://www.python.org/dev/peps/pep-0008/).
* Using a single quoting style everywhere. For whatever reason, I'm sticking to single-quotes.
* Updating `APP_VERSION` that was still left as `1.3`.
* Moving class-variables to instance-variables. Just because `self.foo = 'bar'` always assigns to the instance variables; leaving them as class variables might be misleading. But since the class is instantiated only once, it doesn't matter.
* Searching for `edit-user-config` in two places; and hiding the menu item if it is not found. Makes it easier to run without installing system-wide.
* Searching for the theme-changing scripts and hiding the menu items if not found. Makes the menu cleaner if running without installing system-wide.
* Refactoring `update_menu()`:
    * Split that method into 3 methods: one for updating the GTK+ menu,
      one for parsing a single config line, one for reading/parsing the
      config file.
    * Parsing a config line includes [doctests][], which serves as both
      tests and documentation.
    * Added `--test` to run such [doctests][].
* Removing executable permission from `indicator-chars.desktop`.
* Removing a hidden [\uFE0F codepoint](https://codepoints.net/U+FE0F) from the configuration file. It was showing up as an empty menu item right after the anchor.

I have plans for changing the configuration file format someday in the future, I'll think about it.

[doctests]: https://docs.python.org/2/library/doctest.html

### CODE REVIEW

**Comment by Sadi58** [comment]
Thank you very much for this contribution!

**Comment by Sadi58** [comment]
I'm not very much familiar with either python or github. As a result I made a mistake while trying to test the proposed changes to indicator-chars.py file, and thought it was OK. But later I noticed that the new file created some problems like keeping an instance open when changing its icon. So I reverted back to previous state. I also remembered the rule "when it ain't broken, don't fix it ;-)
FYI.
I intend to look into the cause of that problem etc. when I can spare time for it.

**Comment by denilsonsa** [comment]
Do you have a step-by-step description of how to trigger such bug?

**Comment by Sadi58** [comment]
At this stage all I can say is that when I tested it under Ubuntu 15.04 and Linux Mint 17, I saw a second and then a third indicator in the systray when I simply clicked the menu to change the icon.

**Pull request merged**
